### ISSUE TITLE
Dosn't work with OBS Studio 23 !

### ISSUE THREAD

**Issue by TP555** [jdmclark/jkgfxmod#1]
Good Mod so far , High Quality Graphics and Effects , but it dosn't work with OBS Studio 23 , just Black Screen , too Tested with Bandicam is the same Black Screen  !

TP555

**Comment by GeneralTantor** [comment]
I believe that is just an OBS bug follow this: https://www.youtube.com/watch?v=JN7LrLLfCVM

**Comment by TP555** [comment]
Hey thx for your Answer  :dancer: 

It was run OBS Studio 23 as Admin !!
