### ISSUE TITLE
Idea: Option to disable linear filtering 

### ISSUE THREAD

**Issue by SirYodaJedi** [jdmclark/jkgfxmod#10]
Would it be within the scope of this project to have an option to disable linear texture filtering (while keeping anisotropic filtering enabled)?
For an example, see how [Quake 1 (and other idTech 2+3 games) do it](https://www.quaddicted.com/engines/software_vs_glquake#texture_filtering). Ideally, it would use the equivalent of `gl_nearest_mipmap_linear`, as that lets anisotropic filtering work properly.
I think this would be a great option for people (like me) who want vanilla textures, but would like to take advantage of the project's other features.

**Comment by jdmclark** [comment]
Hi @SirYodaJedi 

Thanks for the suggestion.

To be clear, the original Jedi Knight used bilinear interpolation in hardware mode. If you grew up with a 3D accelerator, the game already looks quite vanilla without any material packs installed.

The software mode did use nearest neighbor sampling, so adding this option would make the textures look about as pixelated as they did in the software renderer. However, compared to Quake, the Jedi Knight software rasterizer used colormaps (palettes) in some pretty creative ways to achieve certain effects. A nearest neighbor option wouldn't be enough to make the game look like you probably remember it. It would be easy enough to add, though.

**Comment by SirYodaJedi** [comment]
I actually usually use the [hidden RGB Emulation rasterizer](https://pcgamingwiki.com/wiki/Star_Wars:_Jedi_Knight_-_Dark_Forces_II#Access_advanced_display_settings_menu), which I'm pretty sure is basically like the 3D accelerated version, but with some stuff missing (like texture filtering). It even has 16-bit colored lighting in Mysteries of the Sith. (I didn't have this game growing up)
Glad to know it isn't too difficult to add; now I just need to figure out how to convert the `.mat` textures to `.png` with the proper color palates.
