### ISSUE TITLE
Add documentation for configuration options

### ISSUE THREAD

**Issue by jdmclark** [jdmclark/jkgfxmod#14]
Currently there isn't really any documentation for the configuration options. Some of these are obvious, but many aren't. It would be helpful to create a separate page explaining what the configuration options do. Ideally these would be accompanied by screenshots, in the case of graphics options.

This page should be created under the docs directory, and should be linked from the main readme.

**Comment by SirYodaJedi** [comment]
Okay. Almost ready; just a couple more questions (and a spellcheck) before I create a pull request.
* So when `log_path` is null, does that mean the injector does not log activity?
* For `data_path` and `log_path`, do they support standard DOS notation for both relative (ex: `..\..\data\jkgfxmod`) and absolute (ex: `C:\ProgramData\jkgfxmod`) paths?

[Status](https://github.com/jdmclark/jkgfxmod/files/3188696/config.md.txt)

**Comment by jdmclark** [comment]
Hello,

Looks good. The only spelling error I see is "explaination", which should be spelled "explanation".

- Correct, when `log_path` is `null` the injector will not write messages to a log file. (That's not 100% accurate since there is also the `JKGM_LOG_PATH` environment variable, but I want to move away from using that.)
- Yes: `data_path` and `log_path` allow both relative and absolute paths, including `..`.
