### ISSUE TITLE
Investigate GOG Galaxy overlay injection using JkGfxMod

### ISSUE THREAD

**Issue by jdmclark** [jdmclark/jkgfxmod#18]
I own copies of the GOG versions.  It wasn't too difficult to figure out how to apply the patch.  The only major difference here is that renaming `inject.exe` to `JKStart.exe` doesn't allow you to access the GOG Galaxy overlay.  However, it does mean you can start the game directly from GOG Galaxy.

_Originally posted by @caitisgreat in https://github.com/jdmclark/jkgfxmod/pull/17#issuecomment-492917388_

I think users generally expect overlays to work, so it would be great if this could be fixed. Note that the Steam overlay does work, so clearly there's something different about the way GOG injects its overlay.

**Comment by SirYodaJedi** [comment]
According to the [store page](https://www.gog.com/game/star_wars_jedi_knight_dark_forces_ii), JKDF2 doesn't have Galaxy overlay support to begin with, so I don't think this is actually a bug.

**Comment by jdmclark** [comment]
Hi @SirYodaJedi 

Thanks for investigating this. I'll close this bug as invalid for now. If this changes or someone believes the overlay should work, we can reopen.
