### ISSUE TITLE
post_box4.frag compile failed due to non-constant offset in textureOffset call

### ISSUE THREAD

**Issue by PhiMue86** [jdmclark/jkgfxmod#29]
![Image 010](https://user-images.githubusercontent.com/41874291/58365874-83b9db80-7eca-11e9-8518-009581e3ce8e.png)

**Comment by jdmclark** [comment]
Hi @Pherim 

Thanks for reporting this issue. This shader appears to unintentionally use a non-compliant nvidia extension that is not supported by your graphics hardware.

I'm attaching an alternative post_box4.frag shader. Could you please copy this attachment over your jkgm/shaders/post_box4.frag file and let me know if it resolves your issue?

Thanks!

[post_box4.frag.txt](https://github.com/jdmclark/jkgfxmod/files/3219191/post_box4.frag.txt)

**Comment by PhiMue86** [comment]
Thank you, it works!

**Comment by jdmclark** [comment]
Thanks @Pherim for the follow-up. I'll cut a new release with this shader ASAP.
