### ISSUE TITLE
How to 32Bit Color ?

### ISSUE THREAD

**Issue by TP555** [jdmclark/jkgfxmod#3]
Hi

- Renders the game in full 32-bit color , but how , im get just 16 !!

here is my Setting:

{
    "resolution": [ 2560, 1080 ],
    "internal_resolution": null,
    "fullscreen": true,
    "hud_scale": 1.5,
    "max_anisotropy": 2.0,
    "enable_ssao": false,
    "enable_parallax": true,
    "command": "jk.exe"
}

How to edit it for 32Bit   ?

**Comment by jdmclark** [comment]
Hi @TP555 

Thanks for the report.

JkGfxMod always uses your desktop color depth. The JK graphics configuration screen will show the display mode as 16-bit, but this is only a side effect of the many convenient lies JkGfxMod is telling JK to get it to render differently.

This is a confusing situation, though, so is a needed documentation change.

**Comment by TP555** [comment]
Re

hmm , i have Win 8.1 , is 32Bit True Color not standard there , or where i can force it  ?
my Main Resolution is 2560x1080@75hz for Windows and Games   !

Or works this just under Win10  ?

**Comment by jdmclark** [comment]
Windows 8 and later automatically force your desktop into a true color mode, so JkGfxMod should always render in true color despite what the JK graphics configuration screen says.

If you've independently verified that the game is using a lower color depth, please check if you have the "reduced colors" compatibility setting enabled. Compatibility options are not required for JkGfxMod.

**Comment by TP555** [comment]
Re

ok , i have no compatibility setting for jk.exe , inject.exe , or Shortcuts  !

im use just a run.bat (+ vbs File to hide the batch Window)

inject.exe -displayconfig      to enable the Advanced Graphics Settings ingame    !
