### ISSUE TITLE
Request: Aspect ratio correction for menus/cutscenes

### ISSUE THREAD

**Issue by bangstk** [jdmclark/jkgfxmod#34]
Currently they are stretched to fill the whole screen even if it's say a 21:9 monitor. I know there's nothing you can do about in-game FOV issues for widescreen, but can there be an option for menus and cutscenes to be letterboxed to a 4:3 aspect ratio instead of stretched? 

Something even cooler would be if the cutscenes could be enlarged (while preserving aspect ratio) to overcome their original letterboxing on widescreen monitors, but that would be a separate work entirely.

**Comment by jdmclark** [comment]
Hi @bangstk 

Thanks for the suggestion. An option to pillarbox menus to 4:3 sounds like a good idea to me.
