### ISSUE TITLE
Idea: Fixing Windowboxing

### ISSUE THREAD

**Issue by SirYodaJedi** [jdmclark/jkgfxmod#36]
_Originally posted by @bangstk in #34:_
>Something even cooler would be if the cutscenes could be enlarged (while preserving aspect ratio) to overcome their original letterboxing on widescreen monitors, but that would be a separate work entirely.

This is a good idea, but I'm not sure how it would work. It might be possible to crop the image before output, but that would crop out the subtitles. 

If possible, it would also be nice if they ignored the "internal resolution", using the output resolution instead. This would prevent windowboxing; if the internal is set to 1440x1080 and the injector output is set to 1920x1080, a JKDF2 cutscene would output at 1920x900 with minor letterboxes, rather than 1440x675 with windowboxing around the whole image.

For what it's worth, JKDF2's cutscenes are 640x300 (2.13:1) and MotS's cutscenes are 640x350 (1.83:1).

**Comment by bangstk** [comment]
Maybe the subtitles can be cropped separately and overlaid (with the black background made transparent) on top of the cropped & resized cutscene, similar to the HUD in-game with scaling.

**Comment by jdmclark** [comment]
This sounds like a good feature, but it's not immediately obvious to me how to reliably tell whether a cutscene or a menu is on screen. This may be another situation where the necessary data simply isn't available. It's worth investigating.

**Comment by jdmclark** [comment]
After 1.5 years, I think I am ready to conclude that there is no reliable way to tell whether a cutscene or a menu is on screen. This would require an executable patch, which is outside the scope for JkGfxMod.

Closing wontfix.
