### ISSUE TITLE
Request: Alternate API

### ISSUE THREAD

**Issue by NikoofDeath** [jdmclark/jkgfxmod#37]
As an AMD (RX 580) GPU owner, it is unfortunate that jkgfxmod relies on OpenGL, as AMD's OpenGL driver remains horrible. For example, with a completely vanilla game, at 1080p with SSAO, Bloom, and 8x MSAA on, I get 50fps with ~40% GPU usage and ~35% CPU usage. Assuming this is an issue with AMD's OpenGL driver and not an issue with the mod itself, an option for a Vulkan or DX renderer would be highly appreciated.

**Comment by bangstk** [comment]
It's SSAO, turn it off and it should run fine. Same story on a GTX 970 (Nvidia)

**Comment by jdmclark** [comment]
Hi @NikoofDeath 

Thanks for the suggestion.

Several performance improvements have been made to JkGfxMod recently. Please try again and let me know if these changes have improved your experience using the AMD OpenGL driver.

The OpenGL renderer seems sufficient for most users. Given limited maintenance time and the lack of compelling use cases for an alternate renderer (besides uncertain performance benefits), I am closing this bug wontfix. I will still consider PRs that implement alternate renderers, should any be submitted.
