### ISSUE TITLE
Crash on level start

### ISSUE THREAD

**Issue by edo3** [jdmclark/jkgfxmod#39]
The game crashes on level startup, the log leaves this error:
`main.cpp|21|debug> DirectDrawCreate hook called
ddraw_impl.cpp|203|debug> DirectDraw::SetCooperativeLevel(Exclusive Fullscreen)
ddraw_impl.cpp|203|debug> DirectDraw::SetCooperativeLevel(Exclusive Fullscreen)
ddraw_impl.cpp|206|debug> DirectDraw::SetCooperativeLevel(Normal)
ddraw_impl.cpp|203|debug> DirectDraw::SetCooperativeLevel(Exclusive Fullscreen)
d3d_impl.cpp|31|debug> Called Direct3D::Initialize, but it is a stub in this version of DirectX`

**Comment by jdmclark** [comment]
Hi edo3,

Thanks for filing this issue.

This crash sounds a lot like #11 (crash at level start when using the
executable that ships with Steam). Can you please confirm whether you are
using the Steam version of the game, and if so, that you have replaced the
game executable per the installation instructions?

If you need a copy of the original executable, you can use a tool called
JKVersions to get it.

Thanks

**Comment by edo3** [comment]
I'm acutally using the GOG version, and the main menu reports 1.0, but after repatching manually to the 1.0 it seems that the problem went away. Thanks

**Comment by jdmclark** [comment]
Thanks for the follow-up. I'm glad to hear the Steam workaround also worked for you.

I've updated #11 to include this information, and I'm closing this bug as a duplicate.

**Comment by rebb** [comment]
> I'm acutally using the GOG version, and the main menu reports 1.0, but after repatching manually to the 1.0 it seems that the problem went away. Thanks

If you don't mind me asking, what does "patching it manually to 1.0" entail ?
I have the GoG 1.0 Version ( according to the menu ), but still get a game crash when using 3D Acceleration once the game loads.
