### ISSUE TITLE
Credits not showing up...

### ISSUE THREAD

**Issue by B-u-R-n-I-n-G-f-I-r-E** [jdmclark/jkgfxmod#44]
After defeating Jerec and after the outro fmv there is the credits screen but is only black, no text at all!
If you press on the credits button in the main menu there is the same problem.
However in windowed mode it is working.

**Comment by jdmclark** [comment]
Hi @B-u-R-n-I-n-G-f-I-r-E 

Thanks for reporting this issue. Some investigation will need to be done to figure out how JK is drawing the credits screen.
