### ISSUE TITLE
MP4 Support for the Videos !

### ISSUE THREAD

**Issue by TP555** [jdmclark/jkgfxmod#52]
Hi

Please Support for MP4 for the Videos + Subtitles Support  (JK/Mots)  !

A Modder did convert all in MP4

https://www.moddb.com/games/star-wars-jedi-knight-dark-forces-ii/downloads/jkdf2fmvs

**Comment by jdmclark** [comment]
Hi @TP555 

Thanks for the suggestion. Unfortunately, implementing this would require extensive modifications to the game executable, so it isn't something JkGfxMod can do.
