### ISSUE TITLE
FOV support?

### ISSUE THREAD

**Issue by madseason666** [jdmclark/jkgfxmod#53]
Hey! first of all, thanks for making this. Works great!
I was wondering if you had FOV support in mind? or if it's possible at all? I've tried patching JK.exe with the IPS patch that's been around for a while, but after doing so the game crashes, sadly. I'm using an original, unmodified CD installation.

Thanks again!

**Comment by SirYodaJedi** [comment]
See #5.

**Comment by madseason666** [comment]
Thanks! that's unfortunate but no biggie I guess. I do not know about any other way to change the FOV outside the IPS patch, which makes this patch crash. I'd rather use this and play in 4:3 then!

EDIT: I was able to use a pre-patched executable found on jkdf2 dot net. Both this and the FOV fix seem to work now. I'm assuming the IPS patch expects some other JK.exe and ends up corrupting it, causing the crashes.
