### ISSUE TITLE
Resolution scaling

### ISSUE THREAD

**Issue by Kroc** [jdmclark/jkgfxmod#59]
I'm getting pretty bad performance for my machine; 1366x768 on Intel HD 5500 graphics. I've disable graphical enhancements. I don't want to lower the resolution because it would not be native to the screen and would look blurry. Could we have a resolution scaling option so that we could set an internal resolution, like 640x480 for the game, and then a scale-factor like 2.0 to get double-size pixels so we can fill the screen better. Alternatively, allow lower-resolutions to be stretched to fill the screen when in windowed mode please.

Asides that complaint, thank you very much for the project!

**Comment by Hamtarotaro** [comment]
Is the MSAA or other antialiasing on?

**Comment by jdmclark** [comment]
Hi @Kroc 

Thanks for the suggestion. Unfortunately, JkGfxMod is really designed for discrete GPUs. The HD 5500 is extremely slow by comparison. I'm not sure how much resolution scaling would help in your situation (or similar situations).

I recommend trying again with a recent version of JkGfxMod, making sure the following configuration changes are made:
- Remove all material packs
- Set `enable_ssao` to `false`
- Set `enable_bloom` to `false`
- Set `antialiasing` to `null`

If this still doesn't work, unfortunately my best recommendation is to play the game in software mode, without using JkGfxMod. This way the game can run on the comparatively much faster CPU.
