### ISSUE TITLE
Consider speculative loading of material images

### ISSUE THREAD

**Issue by jdmclark** [jdmclark/jkgfxmod#6]
Currently, material injection and asset load is performed when JK uploads the corresponding original textures into video memory. This can cause stuttering during gameplay under certain scenarios, since JK does not load textures until immediately before they are needed.

Instead, JkGfxMod could speculatively load materials. Good candidate strategies are not obvious, however. One possibility might be an I/O hook to detect when a level file has been opened, and then parse the level file to extract the anticipated list of materials in advance. More investigation is needed.

**Comment by TP555** [comment]
Re

ah ok , then i hope , my SSD loads the Textures or some Data Faster and minized the short load Lags , i have just installed my Game Current on a 320GB HDD

Without Neuron Textures , it runs all times without loading Lags  !

https://www.youtube.com/watch?v=DHMYbdhPE7M

General or some Performance problems i havn't , is even the first Start while loading the Textures , in my Video , i have run it Second , so no loading laggs  !
