### ISSUE TITLE
Inject.exe does not exist

### ISSUE THREAD

**Issue by Quindorrian** [jdmclark/jkgfxmod#60]
I am having multiple problems with this patch.  First, inject.exe is nowhere in the zipfile.  Also, after doing these steps, what exe do we run to start the game?  Thanks for any help!

**Comment by jdmclark** [comment]
Hi @Quindorrian 

`inject.exe` is part of the release and can be downloaded [here](https://github.com/jdmclark/jkgfxmod/releases/tag/v0.4.0
). You need the `jkgfxmod.zip` file from this page (the other files are for devs or modders). Please see the [doc](https://github.com/jdmclark/jkgfxmod/blob/master/doc/install.md
) for detailed instructions on how to install and run JkGfxMod.

Alternatively, a member of the community has made an unofficial installer. You can find it here: https://www.moddb.com/mods/jedi-knight-remastered

We do not directly support the installer. If you choose to use it and encounter issues, you should report them to the author.

Thanks for the report. Please open a new issue if you encounter specific problems.
