### ISSUE TITLE
Missing Inject.exe

### ISSUE THREAD

**Issue by GeorgeWAmbush** [jdmclark/jkgfxmod#67]
Hey there, feeling like I may be foolish, but the instructions specifically mention an inject.exe and I can only find an inject file.
Thanks

**Comment by jdmclark** [comment]
Hi @GeorgeWAmbush 

`inject.exe` is in the `JkGfxMod.zip` file, which can be found under releases: https://github.com/jdmclark/jkgfxmod/releases

Your operating system may be configured to hide extensions (e.g. the `.exe` part of the filename). This is usually the default. In that case, `inject.exe` would appear to be named `inject`, but it is in fact `inject.exe`.

**Comment by GeorgeWAmbush** [comment]
I actually just downloaded an older build with the inject file still in there, but thanks.
