### ISSUE TITLE
E11 locking up, and forcing weapon switch to fail

### ISSUE THREAD

**Issue by NateThompson114** [jdmclark/jkgfxmod#68]
The E11 will lock up, put a small img in front of the muzzle, then locks the ability to switch weapons.

https://www.twitch.tv/thejedijoe/clip/AbstemiousGracefulHamsterTinyFace

**Comment by jdmclark** [comment]
Hi @NateThompson114 

JkGfxMod cannot cause this problem.

The linked video shows you are using gameplay mods (most likely included in the "Jedi Knight Remastered" mod compilation). I recommend contacting the author(s) of these other mods for support.
