### ISSUE TITLE
Document passing jk.exe command line parameters via inject.exe

### ISSUE THREAD

**Issue by OCircles** [jdmclark/jkgfxmod#69]
In the jkgm.json "command" param, passing the -path argument results in "Failed to launch JK.EXE" message box

`"command": "jk.exe -path log"`
_^ using relative path here, but absolute also fails_

This makes it so that the only way you can run SP mods is having them in your episode folder, which is bad on its own for organizing purposes but then you will also not be able to see modded menu graphics

Ideally you'd be able to **pass arguments from inject.exe itself** so you can use an existing mod manager instead of making one that can modify jkgm.json

I.e. "inject.exe -path log"

**Comment by jdmclark** [comment]
Hi @OCircles 

> Ideally you'd be able to pass arguments from inject.exe itself so you can use an existing mod manager instead of making one that can modify jkgm.json

`inject.exe` already works this way.

For technical reasons, you can't specify command line arguments in config. The correct way to pass command line arguments is by passing them to inject.

This question has come up before, so I'm retasking this issue to address this question in doc.

**Comment by OCircles** [comment]
My bad, I had used an old path that I lifted from a batch file I had used at one point-- turns out I had moved that particular mod. Fixed path in my inject.exe shortcut and I'm running Life of Grismath with beautiful graphics.
