### ISSUE TITLE
60 fps for camera movement

### ISSUE THREAD

**Issue by Patrxgt** [jdmclark/jkgfxmod#70]
Hello,

Is there a possibility to add support for unlocked camera (and other thing, if those are capped too) fps? It's a common issue, that people point out, when they're playing JK, cause framerate of camera is a half of the framerate generated by graphics card and only possibility to change that is capping framerate to 47 or multiply of this number by any even number (eg. 47*2=94 which gives us 94 fps for both the camera framerate and frames generated by graphics card).

I'm asking for this, because (for me, of course) this and better optimization would make this mod an essential for playing Dark Forces II on modern hardware, that would detronize dgVoodoo2, which is good and all, but lacking some neat features this mod provides.

**Comment by jdmclark** [comment]
Hi @Patrxgt 

Unfortunately, this is a problem in the original game executable, and isn't something a wrapper like JkGfxMod can fix.

See #35 for some more discussion (including a suggested binary patch here: https://github.com/jdmclark/jkgfxmod/issues/35#issuecomment-753745276)

**Comment by Patrxgt** [comment]
Well, I think it's possible. Otherwise, there wouldn't be as many mods that add 60fps support to other games. It is enough for your wrapper to listen to the game code in real time and modify the determined values, because only think, that can this method broke is sensitivity, that would been higher, when in 60 fps, but that can be fixed by changing game options, so it isn't that big of a deal.

**Comment by jdmclark** [comment]
Hi @Patrxgt 

Thank you for the suggestion.

Other mods implement 60fps support for other games by directly modifying the game executable. This is not something JkGfxMod is designed to do.

Other projects are trying to address this and similar issues. I recommend checking them out: e.g. https://github.com/shinyquagsire23/OpenJKDF2
